description: Subset GEDI L4A granules within an area of interest (AOI)
algo_name: gedi-subset
version: gedi-subset-0.2.6
environment: ubuntu
repository_url: https://repo.ops.maap-project.org/data-team/maap-documentation-examples.git
docker_url: mas.maap-project.org:5000/root/ade-base-images/r:latest
queue: maap-dps-worker-8gb
build_command: maap-documentation-examples/build.sh
run_command: maap-documentation-examples/gedi-subset/subset.sh
disk_space: 20GB
inputs:
  - name: aoi
    download: True
  - name: columns
    download: False
  - name: query
    download: False
  - name: limit
    download: False
