name: gedi_subset
channels:
  - conda-forge
  - defaults
dependencies:
  - backoff=2.1.2
  - black=22.6.0
  - boto3-stubs=1.24.68
  - boto3-stubs-essential=1.24.68
  - botocore-stubs=1.27.66
  - contextily=1.2.0
  - ipykernel=6.15.2
  - isort=5.10.1
  - memray=1.3.1
  - moto=4.0.2
  # The returns package requires 0.950 because it calls a method of MessageBuilder that
  # was removed from 0.960 for some reason, which is unclear.  Therefore, running mypy
  # with the returns plugin fails when using mypy versions after 0.950.  However, since
  # the returns plugin appears to generate many false positives, it is commented out,
  # and a newer version of mypy is specified instead.
  # - mypy=0.950
  - mypy=0.971
  - pandas-stubs
  - pip
  - pre-commit=2.20.0
  - pytest=7.1.3
  - types-cachetools=5.2.1
  - types-requests=2.28.9
  - pip:
    - filprofiler==2022.9.1
